services:
  my-app:
    privileged: true
    build: # ビルドコンテキストを指定
      context: ./docker # Dockerfileが存在するディレクトリへのパス
      dockerfile: Dockerfile # Dockerfileの名前
      args:
        - UID=${WWWUSER:-1000}
        - GID=${WWWGROUP:-1000}
    container_name: my-app
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./cache:/var/www/cache
    depends_on:
      - my-db

  my-db:
    image: mysql:8.0
    container_name: my-db
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
      MYSQL_PASSWORD: password
    volumes:
      - my-db-data:/var/lib/mysql

volumes:
  my-db-data:
